//! 系统调用编号

pub type OSError = i32;

pub const OSERROR_OK:i32 = 0i32;
pub const OSERROR_PAGETABLE_FLAG_UPDATE_ERROR:i32 = 1i32;
pub const OSERROR_PAGETABLE_VIRT_NOT_FOUND:i32 = 2i32;
pub const OSERROR_PAGETABLE_FRAME_ALLOCFAILED:i32 = 3i32;
pub const OSERROR_PAGETABLE_PAGE_ALREADY_MAPPED:i32 = 4i32;
pub const OSERROR_PAGETABLE_UNKNOWN_ERROR_WHEN_MAP:i32 = 5i32;
pub const OSERROR_PAGETABLE_PAGE_NOT_MAPPED:i32 = 6i32;
pub const OSERROR_PAGETABLE_UNKNOWN_ERROR_WHEN_UNMAP:i32 = 7i32;
pub const OSERROR_PAGETABLE_RAWACCESSTOPAGETABLE:i32 = 8i32;

pub const OSERROR_VMAREA_INVALID_RANGE:i32 = 11i32;
pub const OSERROR_VMAREA_VMSIZE_NOT_EQUAL_TO_PMSIZE:i32 = 12i32;
pub const OSERROR_VMAREA_INVALID_UNMAP:i32 = 13i32;

// 在AREAS/MOD.RS 与 VMM.RS 都可能检查到
pub const OSERROR_PAGEFAULTHANDLER_ACCESS_DENIED:i32 = 21i32;
// 在AREAS/MOD.RS
// 触发缺页异常的页在页表中已经是VALID了
// 目前没有想到用户程序会如何触发这一条，除非是OS本身设计问题
pub const OSERROR_PAGEFAULTHANDLER_TRAP_AT_VALID_PAGE:i32 = 22i32;
// 在VMM.RS
// 一般是因为找不到地址所对应的 VMAREA，
// 相当于表示用户程序传过来的地址不合法
pub const OSERROR_PAGEFAULTHANDLER_UNHANDLED:i32 = 23i32;

pub const OSERROR_PMAREA_OUT_OF_RANGE:i32 = 31i32;
pub const OSERROR_PMAREA_INVALID_RANGE:i32 = 32i32;
pub const OSERROR_PMAREA_SHRINK_FAILED:i32 = 33i32;
pub const OSERROR_PMAREA_SPLIT_FAILED:i32 = 34i32;
pub const OSERROR_PMAREALAZY_RELEASE_NOT_ALLOCATED_PAGE:i32 = 35i32;

// 没有空的*物理*页
pub const OSERROR_MEMORY_RUN_OUT_OF_MEMORY:i32 = 41i32;
// *虚拟*地址空间中找不到足够长的连续空间
pub const OSERROR_MEMORY_RUN_OUT_OF_CONSECUTIVE_MEMORY:i32 = 42i32;
// SYSCALL_MMAP 需要的地址和内核地址相交
pub const OSERROR_MEMORYSET_USER_MMAP_INTERSECT_WITH_KERNEL:i32 = 43i32;
pub const OSERROR_MEMORYSET_INVALID_RANGE:i32 = 44i32;
pub const OSERROR_MEMORYSET_UNMAP_AREA_NOT_FOUND:i32 = 45i32;
pub const OSERROR_MEMORYSET_AREA_NOT_MAPPED:i32 = 46i32;
pub const OSERROR_TASK_MMAP_LENGTH_DISAGREE:i32 = 51i32;

pub const OSERROR_LOADER_PARSE_ELF_FAILED:i32 = 71i32;
pub const OSERROR_LOADER_INVALID_SEGMENT:i32 = 72i32;
pub const OSERROR_LOADER_INVALID_SECTION:i32 = 73i32;
pub const OSERROR_LOADER_APP_NO_TFOUND:i32 = 74i32;
pub const OSERROR_LOADER_CANNOT_PARSE_INTERPRETER:i32 = 75i32;
pub const OSERROR_LOADER_PHDR_NOT_FOUND:i32 = 76i32;
pub const OSERROR_LOADER_SKIPPED:i32 = 77i32;

pub const OSERROR_TASK_NO_TRAP_HANDLER:i32 = 81i32;
// 申请 PHYSICAL MEMORY 中的物理页面失败
pub const OSERROR_TASK_RUN_OUT_OF_MEMORY:i32 = 82i32;

// CPU 找不到刚刚切换出来的任务
pub const OSERROR_CPULOCAL_SWITCHED_FROM_EMPTY_TASK:i32 = 91i32;

// 文件描述符已满，无法再分配了
pub const OSERROR_FDMANAGER_NO_AVAILABLE_FD:i32 = 101i32;
// 找不到要求的文件描述符
pub const OSERROR_FDMANAGER_FD_NOT_FOUND:i32 = 102i32;